sudo: required
services:
  - docker

before_install:
  - docker build -t ram/docker-react -f Dockerfile.dev .

script:
  - docker run ram/docker-react npm run test -- --coverage
  - docker run -e CI=true ram/docker-react npm run test
