FROM node:alpine as builder
WORKDIR '/usr/frontendapp'
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx
COPY --from=builder /usr/frontendapp/build /usr/share/nginx/html